KEYMAPOPTS="us us"
HOSTNAMEOPTS="-n ${HOSTNAME}"
INTERFACESOPTS="auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
    hostname ${HOSTNAME}"
DNSOPTS="-d localdomain 1.1.1.1"
TIMEZONEOPTS="${TZ}"
PROXYOPTS="none"
APKREPOSOPTS="-1"
USEROPTS="-a -g wheel root"
SSHDOPTS="-c openssh"
NTPOPTS="-c busybox"
DISKOPTS="-m sys /dev/mmcblk0"
