KEYMAPOPTS="us us"
HOSTNAMEOPTS="-n wipi-server"
INTERFACESOPTS="auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
${WIFI_SSID:+
auto wlan0
iface wlan0 inet dhcp
    pre-up wpa_supplicant -B -D nl80211 -i wlan0 -c <(wpa_passphrase \"${WIFI_SSID}\" \"${WIFI_PASSWD}\")
    post-down killall wpa_supplicant
}"
DNSOPTS="-d cf-dom.com 1.1.1.1"
TIMEZONEOPTS="UTC"
PROXYOPTS="none"
APKREPOSOPTS="-1"
USEROPTS="-a -g wheel root"
SSHDOPTS="-c openssh"
NTPOPTS="-c busybox"
DISKOPTS="-m sys /dev/mmcblk0"
