# client wireguard config - dual-endpoint method

[Interface]
PrivateKey = ${CLIENT_PRIVATE_KEY}
Address = ${CLIENT_ADDRESS}
DNS = ${PIHOLE_IP}

[Peer]
PublicKey = ${SERVER_A_PUBLIC_KEY}
AllowedIPs = 0.0.0.0/0
Endpoint = ${WIREGUARD_DOMAIN_A}:51820
PersistentKeepalive = 25

[Peer]
PublicKey = ${SERVER_B_PUBLIC_KEY}
AllowedIPs = 0.0.0.0/0
Endpoint = ${WIREGUARD_DOMAIN_B}:51820
PersistentKeepalive = 25