# client wireguard config - dns failover method

[Interface]
PrivateKey = ${CLIENT_PRIVATE_KEY}
Address = ${CLIENT_ADDRESS}
DNS = ${PIHOLE_IP}

[Peer]
PublicKey = ${SERVER_PUBLIC_KEY}
AllowedIPs = 0.0.0.0/0
Endpoint = ${WIREGUARD_DOMAIN}:51820
PersistentKeepalive = 25