ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
    ssid="${WIFI_SSID}"
    psk="${WIFI_PASSWD}"
}

# put this into alpine wifi config (wipi over wifi)
${WIFI_SSID:+
auto wlan0
iface wlan0 inet dhcp
    pre-up wpa_supplicant -B -D nl80211 -i wlan0 -c <(wpa_passphrase \"${WIFI_SSID}\" \"${WIFI_PASSWD}\")
    post-down killall wpa_supplicant
} >> /etc/network/interfaces
